package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	"github.com/nixmaldonado/skytrack/graph/model"
)

// Airline is the resolver for the airline field.
func (r *flightResolver) Airline(ctx context.Context, obj *model.Flight) (*model.Airline, error) {
	// N+1: this runs once PER FLIGHT — 8 flights = 8 separate "queries"
	airlineID := r.Store.FlightAirlineID(obj.ID)
	return r.Store.FindAirlineByID(airlineID), nil
}

// DepartureAirport is the resolver for the departureAirport field.
func (r *flightResolver) DepartureAirport(ctx context.Context, obj *model.Flight) (*model.Airport, error) {
	// N+1: another query per flight
	airportID := r.Store.FlightDepartureAirportID(obj.ID)
	return r.Store.FindAirportByID(airportID), nil
}

// ArrivalAirport is the resolver for the arrivalAirport field.
func (r *flightResolver) ArrivalAirport(ctx context.Context, obj *model.Flight) (*model.Airport, error) {
	// N+1: another query per flight
	airportID := r.Store.FlightArrivalAirportID(obj.ID)
	return r.Store.FindAirportByID(airportID), nil
}

// Flights is the resolver for the flights field.
func (r *queryResolver) Flights(ctx context.Context) ([]model.Flight, error) {
	return r.Store.AllFlights(), nil
}

// Flight returns FlightResolver implementation.
func (r *Resolver) Flight() FlightResolver { return &flightResolver{r} }

type flightResolver struct{ *Resolver }
