package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"encoding/base64"
	"strconv"

	"github.com/nixmaldonado/skytrack/graph/model"
)

// CreateAirport is the resolver for the createAirport field.
func (r *mutationResolver) CreateAirport(ctx context.Context, input model.CreateAirportInput) (*model.Airport, error) {
	return r.Store.Create(input)
}

// UpdateAirport is the resolver for the updateAirport field.
func (r *mutationResolver) UpdateAirport(ctx context.Context, icao model.ICAOCode, input model.UpdateAirportInput) (*model.Airport, error) {
	return r.Store.Update(icao, input)
}

// Airports is the resolver for the airports field.
func (r *queryResolver) Airports(ctx context.Context, first *int, after *string) (*model.AirportConnection, error) {
	limit := 25
	if first != nil {
		limit = *first
	}

	airports := r.Store.All()

	startIdx := 0
	if after != nil {
		decoded, err := base64.StdEncoding.DecodeString(*after)
		if err == nil {
			idx, err := strconv.Atoi(string(decoded))
			if err == nil {
				startIdx = idx + 1
			}
		}
	}

	total := len(airports)
	if startIdx > total {
		startIdx = total
	}
	endIdx := startIdx + limit
	if endIdx > total {
		endIdx = total
	}
	page := airports[startIdx:endIdx]

	edges := make([]model.AirportEdge, len(page))
	for i, a := range page {
		cursor := base64.StdEncoding.EncodeToString([]byte(strconv.Itoa(startIdx + i)))
		airport := a
		edges[i] = model.AirportEdge{
			Cursor: cursor,
			Node:   &airport,
		}
	}

	hasNext := endIdx < total
	hasPrev := startIdx > 0
	var startCursor, endCursor *string
	if len(edges) > 0 {
		startCursor = &edges[0].Cursor
		endCursor = &edges[len(edges)-1].Cursor
	}

	return &model.AirportConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage:     hasNext,
			HasPreviousPage: hasPrev,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
		TotalCount: total,
	}, nil
}

// Airport is the resolver for the airport field.
func (r *queryResolver) Airport(ctx context.Context, icao model.ICAOCode) (*model.Airport, error) {
	return r.Store.FindByICAO(icao), nil
}

// AirportByIata is the resolver for the airportByIata field.
func (r *queryResolver) AirportByIata(ctx context.Context, iata model.IATACode) (*model.Airport, error) {
	return r.Store.FindByIATA(iata), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
