package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"

	"github.com/nixmaldonado/skytrack/graph/model"
)

// TrackFlight is the resolver for the trackFlight field.
func (r *subscriptionResolver) TrackFlight(ctx context.Context, icao24 string) (<-chan *model.FlightPosition, error) {
	// 1. Tell the poller to start tracking this aircraft
	r.Poller.Track(icao24)

	// 2. Subscribe to Redis channel for position updates
	ch, cleanup := r.PubSub.Subscribe(ctx, icao24)

	// 3. Clean up when client disconnects (ctx cancelled by gqlgen)
	go func() {
		<-ctx.Done()
		cleanup()
		r.Poller.Untrack(icao24)
	}()

	// 4. Return the channel — gqlgen streams each value to the client
	return ch, nil
}
