// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Airport struct {
	ID        string      `json:"id"`
	Icao      ICAOCode    `json:"icao"`
	Iata      *IATACode   `json:"iata,omitempty"`
	Name      string      `json:"name"`
	City      *string     `json:"city,omitempty"`
	Country   string      `json:"country"`
	Latitude  float64     `json:"latitude"`
	Longitude float64     `json:"longitude"`
	Elevation *int        `json:"elevation,omitempty"`
	Type      AirportType `json:"type"`
}

type AirportConnection struct {
	Edges      []AirportEdge `json:"edges"`
	PageInfo   *PageInfo     `json:"pageInfo"`
	TotalCount int           `json:"totalCount"`
}

type AirportEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Airport `json:"node"`
}

type CreateAirportInput struct {
	Icao      ICAOCode    `json:"icao"`
	Iata      *IATACode   `json:"iata,omitempty"`
	Name      string      `json:"name"`
	City      *string     `json:"city,omitempty"`
	Country   string      `json:"country"`
	Latitude  float64     `json:"latitude"`
	Longitude float64     `json:"longitude"`
	Elevation *int        `json:"elevation,omitempty"`
	Type      AirportType `json:"type"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type UpdateAirportInput struct {
	Iata      *IATACode    `json:"iata,omitempty"`
	Name      *string      `json:"name,omitempty"`
	City      *string      `json:"city,omitempty"`
	Country   *string      `json:"country,omitempty"`
	Latitude  *float64     `json:"latitude,omitempty"`
	Longitude *float64     `json:"longitude,omitempty"`
	Elevation *int         `json:"elevation,omitempty"`
	Type      *AirportType `json:"type,omitempty"`
}

type AirportType string

const (
	AirportTypeLarge        AirportType = "LARGE"
	AirportTypeMedium       AirportType = "MEDIUM"
	AirportTypeSmall        AirportType = "SMALL"
	AirportTypeHeliport     AirportType = "HELIPORT"
	AirportTypeSeaplaneBase AirportType = "SEAPLANE_BASE"
	AirportTypeClosed       AirportType = "CLOSED"
)

var AllAirportType = []AirportType{
	AirportTypeLarge,
	AirportTypeMedium,
	AirportTypeSmall,
	AirportTypeHeliport,
	AirportTypeSeaplaneBase,
	AirportTypeClosed,
}

func (e AirportType) IsValid() bool {
	switch e {
	case AirportTypeLarge, AirportTypeMedium, AirportTypeSmall, AirportTypeHeliport, AirportTypeSeaplaneBase, AirportTypeClosed:
		return true
	}
	return false
}

func (e AirportType) String() string {
	return string(e)
}

func (e *AirportType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AirportType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AirportType", str)
	}
	return nil
}

func (e AirportType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AirportType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AirportType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
