// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Airline struct {
	ID      string  `json:"id"`
	Icao    string  `json:"icao"`
	Iata    *string `json:"iata,omitempty"`
	Name    string  `json:"name"`
	Country string  `json:"country"`
}

type Airport struct {
	ID        string      `json:"id"`
	Icao      ICAOCode    `json:"icao"`
	Iata      *IATACode   `json:"iata,omitempty"`
	Name      string      `json:"name"`
	City      *string     `json:"city,omitempty"`
	Country   string      `json:"country"`
	Latitude  float64     `json:"latitude"`
	Longitude float64     `json:"longitude"`
	Elevation *int        `json:"elevation,omitempty"`
	Type      AirportType `json:"type"`
}

type AirportConnection struct {
	Edges      []AirportEdge `json:"edges"`
	PageInfo   *PageInfo     `json:"pageInfo"`
	TotalCount int           `json:"totalCount"`
}

type AirportEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Airport `json:"node"`
}

type CreateAirportInput struct {
	Icao      ICAOCode    `json:"icao"`
	Iata      *IATACode   `json:"iata,omitempty"`
	Name      string      `json:"name"`
	City      *string     `json:"city,omitempty"`
	Country   string      `json:"country"`
	Latitude  float64     `json:"latitude"`
	Longitude float64     `json:"longitude"`
	Elevation *int        `json:"elevation,omitempty"`
	Type      AirportType `json:"type"`
}

type Flight struct {
	ID               string       `json:"id"`
	Callsign         string       `json:"callsign"`
	Airline          *Airline     `json:"airline,omitempty"`
	DepartureAirport *Airport     `json:"departureAirport,omitempty"`
	ArrivalAirport   *Airport     `json:"arrivalAirport,omitempty"`
	Status           FlightStatus `json:"status"`
}

type FlightConnection struct {
	Edges      []FlightEdge `json:"edges"`
	PageInfo   *PageInfo    `json:"pageInfo"`
	TotalCount int          `json:"totalCount"`
}

type FlightEdge struct {
	Cursor string  `json:"cursor"`
	Node   *Flight `json:"node"`
}

type FlightFilter struct {
	AirlineID          *string       `json:"airlineId,omitempty"`
	DepartureAirportID *string       `json:"departureAirportId,omitempty"`
	ArrivalAirportID   *string       `json:"arrivalAirportId,omitempty"`
	Status             *FlightStatus `json:"status,omitempty"`
}

type FlightPosition struct {
	Icao24       string   `json:"icao24"`
	Callsign     *string  `json:"callsign,omitempty"`
	Latitude     *float64 `json:"latitude,omitempty"`
	Longitude    *float64 `json:"longitude,omitempty"`
	Altitude     *float64 `json:"altitude,omitempty"`
	Velocity     *float64 `json:"velocity,omitempty"`
	Heading      *float64 `json:"heading,omitempty"`
	VerticalRate *float64 `json:"verticalRate,omitempty"`
	OnGround     bool     `json:"onGround"`
	Timestamp    int      `json:"timestamp"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type Subscription struct {
}

type UpdateAirportInput struct {
	Iata      *IATACode    `json:"iata,omitempty"`
	Name      *string      `json:"name,omitempty"`
	City      *string      `json:"city,omitempty"`
	Country   *string      `json:"country,omitempty"`
	Latitude  *float64     `json:"latitude,omitempty"`
	Longitude *float64     `json:"longitude,omitempty"`
	Elevation *int         `json:"elevation,omitempty"`
	Type      *AirportType `json:"type,omitempty"`
}

type AirportType string

const (
	AirportTypeLarge        AirportType = "LARGE"
	AirportTypeMedium       AirportType = "MEDIUM"
	AirportTypeSmall        AirportType = "SMALL"
	AirportTypeHeliport     AirportType = "HELIPORT"
	AirportTypeSeaplaneBase AirportType = "SEAPLANE_BASE"
	AirportTypeClosed       AirportType = "CLOSED"
)

var AllAirportType = []AirportType{
	AirportTypeLarge,
	AirportTypeMedium,
	AirportTypeSmall,
	AirportTypeHeliport,
	AirportTypeSeaplaneBase,
	AirportTypeClosed,
}

func (e AirportType) IsValid() bool {
	switch e {
	case AirportTypeLarge, AirportTypeMedium, AirportTypeSmall, AirportTypeHeliport, AirportTypeSeaplaneBase, AirportTypeClosed:
		return true
	}
	return false
}

func (e AirportType) String() string {
	return string(e)
}

func (e *AirportType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AirportType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AirportType", str)
	}
	return nil
}

func (e AirportType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AirportType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AirportType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FlightStatus string

const (
	FlightStatusScheduled FlightStatus = "SCHEDULED"
	FlightStatusActive    FlightStatus = "ACTIVE"
	FlightStatusLanded    FlightStatus = "LANDED"
	FlightStatusCancelled FlightStatus = "CANCELLED"
)

var AllFlightStatus = []FlightStatus{
	FlightStatusScheduled,
	FlightStatusActive,
	FlightStatusLanded,
	FlightStatusCancelled,
}

func (e FlightStatus) IsValid() bool {
	switch e {
	case FlightStatusScheduled, FlightStatusActive, FlightStatusLanded, FlightStatusCancelled:
		return true
	}
	return false
}

func (e FlightStatus) String() string {
	return string(e)
}

func (e *FlightStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FlightStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FlightStatus", str)
	}
	return nil
}

func (e FlightStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FlightStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FlightStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
